package com.comtrade.constants;

public enum Operations {
	SAVE, 
	SAVE_ALL_PROPERTY_INFO, 
	RETURN_PROPERTY_FOR_OWNER, 
	LOGIN_USER, 
	DELETE, 
	UPDATE, 
	RETURN_ALL, 
	RETURN_BOOKING_FOR_PROPERTY,
	NOTIFY_HOST_WTIH_NEW_BOOKING, 
	NOTIFY_ALL_USERS_WITH_NEW_BOOKINGS, 
	RETURN_BOOKING_FOR_USER
}
